name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # rodar todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone github-stats
        run: |
          git clone https://github.com/jstrieb/github-stats.git github-stats

      - name: Install dependencies
        run: |
          cd github-stats
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run github-stats
        env:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd github-stats
          python3 generate_images.py

      - name: Commit and push generated images
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add generated/*.svg
          git diff --quiet && echo "No changes to commit" || git commit -m "Update GitHub stats images [skip ci]"
          git push
