name: Generate GitHub Stats

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  github-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Generate GitHub Stats
        uses: jstrieb/github-stats@main
        with:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          EXCLUDE_REPOS: ""
          EXCLUDE_FORKED: false

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add generated/
          git diff --staged --quiet || git commit -m "📊 Updated GitHub stats"
          git push
